### ISSUE TITLE
Most vars are private

### ISSUE THREAD

**Issue by stevenklar** [Arc8ne/GH-Boot-Sequence-Animation-Skipper#1]
Hey, I got issues compling as most of the vars are actually private.
Was it developed for an older version or did you modify the Assembly on your side?

**Comment by Arc8ne** [comment]
Hi there, sorry for the delayed response.

With regards to the issue that you mentioned, you will need to reference a publicized version of the game's assembly (and enable the "Allow unsafe code" option if you are building the project using Visual Studio) prior to building (i.e. compiling) the project.
